[package]
name = "embeddable-config"
version = "0.1.0"
authors = ["Shinichi Kogai <kogai0121@gmail.com>"]

[dependencies]
serde = "1.0.60"
serde_derive = "1.0.60"
serde_json = "1.0.17"
# serde_json = { version = "1.0", optional = true }
quote = "0.6"
